language: python
python:
  - "3.4"
  - "3.5"
sudo: false
env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
cache:
  directories:
    - $HOME/.cache/pip
install:
 - pip install "pip<8.0.0" wheel
 - pip install "$DJANGO" "coverage==3.7.1"
 - pip install -e .
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django<1.9"
    - python: "3.5"
      env: DJANGO="Django<1.9"
branches:
 only:
  - master
script:
  - cd tests && coverage run manage.py test test_app
after_success:
  - cd tests && coverage report