language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
sudo: false
env:
  matrix:
   - DJANGO="Django<1.7"
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
cache:
  directories:
    - $HOME/.cache/pip
install:
 # pip >=8 dropped Python 3.2 support
 - pip install "pip<8.0.0" wheel
 - pip install "$DJANGO" "coverage==3.7.1"
 - pip install .
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django<1.7"
    - python: "3.4"
      env: DJANGO="Django<1.8"
    - python: "3.5"
      env: DJANGO="Django<1.10"
branches:
 only:
  - master
script:
  - coverage run manage.py test test_app
after_success:
  - coverage report